const cards = [
  {
    title: "projects.amigosDoFuturo.title",
    subtitle: "projects.amigosDoFuturo.subtitle",
    description: "projects.amigosDoFuturo.description",
    image: "src/assets/images/projects/amigos-do-futuro.png",
    link: "https://lucasmonteiro58.github.io/AmigosdoFuturo/",
    linkCode: "https://github.com/lucasmonteiro58/AmigosdoFuturo",
    tags: ["Javascript", "HTML", "CSS", "JQuery"],
  },
  {
    title: "projects.weatherApp.title",
    subtitle: "projects.weatherApp.subtitle",
    description: "projects.weatherApp.description",
    image: "src/assets/images/projects/weather-app.png",
    link: "https://weather-app-by-lucas.netlify.app/",
    linkCode: "https://github.com/lucasmonteiro58/weather-app",
    tags: ["Vue", "TypeScript", "Vite", "RapidAPI", "Tailwind"],
  },
  {
    title: "projects.emaranhados.title",
    subtitle: "projects.emaranhados.subtitle",
    description: "projects.emaranhados.description",
    image: "src/assets/images/projects/emaranhados.png",
    link: "https://emaranhados-site.netlify.app/#/",
    linkCode: "",
    tags: ["Javascript", "HTML", "CSS", "Vue"],
  },
  {
    title: "projects.lyriks.title",
    subtitle: "projects.lyriks.subtitle",
    description: "projects.lyriks.description",
    image: "src/assets/images/projects/lyriks.png",
    link: "https://lyriks-by-lucas.netlify.app/",
    linkCode: "https://github.com/lucasmonteiro58/lyriks",
    tags: ["Javascript", "HTML", "CSS", "React", "Vite"],
  },
  {
    title: "projects.infoVirus.title",
    subtitle: "projects.infoVirus.subtitle",
    description: "projects.infoVirus.description",
    image: "src/assets/images/projects/infovirus.png",
    link: "https://info-virus-v3.netlify.app/",
    linkCode: "",
    tags: ["Javascript", "HTML", "CSS", "Vue"],
  },
  {
    title: "projects.luzDoSaber.title",
    subtitle: "projects.luzDoSaber.subtitle",
    description: "projects.luzDoSaber.description",
    image: "src/assets/images/projects/luz_do_saber.png",
    link: "https://appluzdosaber.seduc.ce.gov.br/#/",
    linkCode: "",
    tags: ["Javascript", "HTML", "CSS", "Vue"],
  },

  {
    title: "projects.mideBalanca.title",
    subtitle: "projects.mideBalanca.subtitle",
    description: "projects.mideBalanca.description",
    image: "src/assets/images/projects/mide-balanca.png",
    link: "https://mide-balanca-interativa.netlify.app/#/",
    linkCode: "",
    tags: ["Javascript", "HTML", "CSS", "Vue", "Nuxt"],
  },
  {
    title: "projects.mideIlha.title",
    subtitle: "projects.mideIlha.subtitle",
    description: "projects.mideIlha.description",
    image: "src/assets/images/projects/mide-ilha.png",
    link: "https://mide-ilha-das-operacoes-3.netlify.app/#/",
    linkCode: "",
    tags: ["Javascript", "HTML", "CSS", "Vue", "Nuxt"],
  },
  {
    title: "projects.keepVue.title",
    subtitle: "projects.keepVue.subtitle",
    description: "projects.keepVue.description",
    image: "src/assets/images/projects/keep-vue.png",
    link: "https://vue-keep.netlify.app/",
    linkCode: "https://github.com/lucasmonteiro58/keep-clone",
    tags: ["Vue", "TypeScript", "Vite", "Firebase", "Tailwind", "PWA"],
  },
];

export default cards;
